### ISSUE TITLE
Small improvments for Modul 4

### ISSUE THREAD

**Issue by Alec-SE** [GIScience/gis-training-resource-center#13]
__Graphical Variables and Symbology__

- [x] When you want to explain where to click and where to click next use the `Code` text style by putting the text in `` . For Example in "Styling Panel" you could say `View` -> `Panels`  -> `Layer Styling`
- [x] Styling panel: "1. Right-click on the layer you wish to style and select properties." Add the step to open the symbology tab in the Properties Panel.
- [x] [Add Invert colour ramp](https://gis.stackexchange.com/questions/273430/invert-color-ramp-in-qgis-3-0) 
- [x] Add a section on saving and exporting styles and how to use styles one receives from somebody else. For example, if an organization has standard styles. [Video](https://www.youtube.com/watch?v=2N5ZyFlbqSQ)
- [x] Show how to add more symbols to QGIS. You can use UN and Red Cross symbols with the [Plugin Resource Sharing](https://www.youtube.com/watch?v=7N6u3VWzNpM). And there is a way to add [SVG](https://docs.qfield.org/how-to/map-styling/) 
- [x] Add how to move labels

__Print Layout__

- [x] Add some more details ad "Adding a legend" e.g. how to use a two-column legend.
- [x] Add a Video on how to add an overview map.
- [x] Add how to add an image e.g. a logo to the map.
- [x] Add how to export the map and in which formats
- [x] Add a section on how to create and use map templates.
- [x] Add a large section on QGIS [Atlas](https://docs.qgis.org/3.28/en/docs/training_manual/forestry/forest_maps.html) function. [Video](https://www.youtube.com/watch?v=LB0OsU8cni8)

**Comment by enauj** [comment]
Finished with the tasks
