### ISSUE TITLE
Error in image 35 - "Temporal" vs "Temporary"

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#145]
Image 35 showing folder structure (used [here](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_basic_data_processing.html#id1) and [here](https://giscience.github.io/gis-training-resource-center/content/Modul_1/en_qgis_interface_ex2.html#standard-folder-structure) - it explains the "temp" folder as "Temporal results". I think this should be "Temporary results".

**Comment by enauj** [comment]
fixed
