### ISSUE TITLE
Module 3 Exercise 7 - Somalia georeferencing 

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#148]
1. The link to download the data is missing
should be https://nexus.heigit.org/repository/gis-training-resource-center/Module_3/Exercise_7/Module_3_Exercise_7_Georeferencing.zip ?

2. On the exercises page this is listed as Module 3 exercise 7, but in the URL it is `module_3_ex_5_georeferencing.html` - update the URL

**Comment by enauj** [comment]
fixed
