### ISSUE TITLE
do not push unneccessary files

### ISSUE THREAD

**Issue by maze2point0** [GIScience/gis-training-resource-center#15]
Make sure to not push not needed files like

empty files

or `.DS_Store`

https://en.wikipedia.org/wiki/.DS_Store
 https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository

**Comment by celthome** [comment]
I added .DS_Store into the gitignore file and deleted the existing .DS_Store files from this repository, so with the next pull for everyone this problem should be solved.
