### ISSUE TITLE
Module 1: create a training setup section

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#24]
In Module 1: Getting started with QGIS, the section **Exercise: Create a new QGIS project** starts with "In your GIS_Training folder..."

This is the first mention of a GIS_Training folder - does there need to be a section somwhere where people are guided on any steps to take/files to download/folders to create before they start the training?

**Comment by isikl** [comment]
Not sure how the page looked like mid March, but do you have and particular steps in mind? The Exercise is about getting familiar with the QGIS gui, the template folder is introduced and no furthers steps are needed in my opinion. But maybe it can be mentioned, that the folder can be used for any future projects.

**Comment by isikl** [comment]
Any particular steps in mind? Maybe some preparation steps can be also included in the Trainers corner.

**Comment by enauj** [comment]
QGIS installation guide has been replaced with a setting up for the training subchaper where we mention the folders.
