### ISSUE TITLE
Feedback Modul 1

### ISSUE THREAD

**Issue by celthome** [GIScience/gis-training-resource-center#27]
Nice Modul! Fixed some small typos :-)

## Feedback:
- [x] add sources for the images
- [x] go over the  comments in markdown
- [x] Exercise 1: Understanding the Interface. In the folder structure that the people should download are some errors:
       - [ ] fix naming (--> Module)
       - [ ] no Excercise 0 (either rename in chapter or in the file)
       - [ ] Handout name German, not able to open, necessary? if not delete
- [x] and as already here mentioned: https://github.com/GIScience/gis-training-resource-center/issues/25#issue-2179617617 I agree, the installation part should be before getting started

**Exercises:**
So there are 3 Markdown files with exercises, but only one gets displayed online. I'll try to break it down so you can decide which should be deleted, changed etc. I think @Alec-SE should have a look here.
The 3 Exercises:

- Exercise 1: Understanding the Interface (content/Modul_1/en_qgis_interface_ex2.md)
    - the one that gets displayed, is fine
- Exercise 0: Understanding the Interface (content/Modul_1/en_qgis_interface_ex2) (no .md ending!)
    - link to data is missing, seems to be an outdated version of the one above, could be deleted. 
- QGIS Exercise 1: Understand the user interface and get to know the layer concept (content/Modul_1/en_qgis_interface_ex1.md)
    - download link to data is missing and not displayed online

**Comment by ioalexei** [comment]
Thanks - probably best to hold off making significant changes to Modules 1-3 while I'm still reviewing, there will be some bigger things that need to be addressed as well
