### ISSUE TITLE
Issue on page /content/Modul_2/en_qgis_modul_2_exercises.html

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#43]
Page is missing Data Sources exercises

**Comment by isikl** [comment]
Please check for all modules, if all exercises are listed in the module exercise list, e.g.: https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_modul_2_exercises.html

**Comment by enauj** [comment]
issue was fixed when the exercise page layout got changed
