### ISSUE TITLE
Issue on page /content/Modul_3/en_qgis_digitalisation_ex2.html

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#46]
The file name says exercise 2 but the page title says page 1 - clarify/fix

**Comment by isikl** [comment]
And: 

- [ ] Missing/Faulty wiki link under Map Road Block 2. : https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_digitalisation_ex2.html#map-road-blocs

**Comment by isikl** [comment]
@ioalexei which file name do you mean? Couldn't find any. In some screenshots it says "ex2", but I think it is not that relevant?

**Comment by ioalexei** [comment]
The markdown file for this section is `en_qgis_digitalisation_ex2.md` but in the contents list it's listed as "Exercise 1" - similar mismatch for other exercises in this section

**Comment by isikl** [comment]
#26

**Comment by enauj** [comment]
#98
