### ISSUE TITLE
Missing images in Selection and Queries Exercise 1

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#48]
Images linked under  "Extract by Attribute" near the bottom of the page are missing

**Comment by isikl** [comment]
And: 

- [ ] Below of box: Numbering is inncorrext and quote is missing: "6. Find the tool Extract by Expression in the `Toolbox. 1."

**Comment by enauj** [comment]
fixed the exercise in commit bf80e3e86aeea1b8ba6a36bb5c86bbf28c6adc80
