### ISSUE TITLE
Missing image sources in Print Layout page 

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#49]
Missing image under "Sources"

**Comment by isikl** [comment]
@ioalexei Is this still valid? Please check and close the issue or specify. Thanks!

**Comment by ioalexei** [comment]
Some images on this page are from CartONG: 
https://giscience.github.io/gis-training-resource-center/content/Modul_4/en_qgis_map_design_2.html

Where they are from CartONG, the source should be given in the caption. 

Better would be to use our own screenshots and not ones from CartONG

**Comment by ioalexei** [comment]
Re-reading the initial issue comment, I'm actually not sure that's what it was referring to. But since this still needs to be addressed, I've change the issue title and will add a separate one about where it would be helpful to have more example images on that page.
