### ISSUE TITLE
Context sections in "Examples of Good Map Design" are empty

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#51]
https://giscience.github.io/gis-training-resource-center/content/Modul_4/en_qgis_map_examples.html

The sections in this page which give context on the maps are empty

**Comment by isikl** [comment]
@ioalexei This is fixed? Please check and close the issue or specify. thanks!

**Comment by ioalexei** [comment]
Yes, looks like this is fixed by https://github.com/GIScience/gis-training-resource-center/commit/33b581f82a6002dd1f5bcb95c858ac50fe34a293
