### ISSUE TITLE
Improve example images for "What is Geodata?" section

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#57]
In the ___What is Geodata___ subsection under ___Module 2: Intro to geodata___, the supporting images could be improved. 

"In the case of the geometric representation of [features vs table form](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept.html#geometry-geodata-example), or in the case of the table where [non-geographic attributes are just ID codes](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept.html#geodata-example) and are not helpful to explain the difference between spatial and non-spatial information

Something like the images below would be a better support to explain those concepts:
![image](https://github.com/GIScience/gis-training-resource-center/assets/3179403/755dc6c0-43bd-409b-b1bd-9450a7e83711)
"
(_Francesco C. can provide the original quality versions of the images in this screenshot_)

**Comment by ioalexei** [comment]
- Related comment: On [Fig 15](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept.html#geodata-example) - the name is not spatial information, image should be updated

**Comment by enauj** [comment]
Improved the introduction of geodata and explanation of vector data with the BRC material.
(6849ba2)

https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept.html

Feedback is appreciated.

**Comment by ioalexei** [comment]
This is looking great! Apologies for being slow to review. Some initial comments from reading through the updated content: 

1. Under vector file formats: 
  - in the table it says gpkg is the new standard, but it's not mentioned in the part below, 'Most common formats'
  - It says gdb and geojson are similar to shapefile - not sure I agree with this?
  - KMZ is included without an explanation on what it is 
  - GDB is mentioned in common formats but isn't in the table 
  - I think it's worth noting that GDB and GPKG are databases compared to the others which are files 
  - Think important to note geojson can't store projection info & is conventionally limited to WGS84 
  
Perhaps we could remove the second section, "Most common formats" and just use the table to convey the necessary information? 

2. Under raster data formats, can we remind that gdb and gpkg can hold raster data?
3. Under 'The layer concept', there's a reference to CartONG. Looking at the linked material, I think it's ok to just keep the CartONG reference in the image caption and leave out the one in the text - since we aren't using text references/footnotes elsewhere. 
4. The TrueSizeOf embed doesn't work for me - it has an undismissable popup and a note underneath about it being embedded. I think the embed can be remove anyway, since there is already a screenshot and a link to the page. 
5. Under 'How to choose an appropriate projected coordinate system' it says "The data and the project should always be the same, or else you will get wrong results! " - this isn't quite right. Data and project can have different CRS and QGIS will reconcile them. But they need to be in the same CRS for accurate analysis against other layers and various other operations. Think it's also important to note that every data set should have it's own CRS and that changing a layer's CRS to something it wasn't encoded in will result in errors. 
6. "EPSG" needs to be explained on first use - and perhaps explain the difference between the CRS name and EPSG code?
7. Source link for fig 24 doesn't work for me 
8. Fig 26-29 are missing source info
9. In the discussion of different reference systems, it might be helpful to show an example of different coordinate systems for the same point - e.g. (44.173, 5.278) in WGS84  is (1912532.92, 835466.28) in ED50 (epsg:2192)

**Comment by enauj** [comment]
added the points from the feedback in commit e316bf5d7f07b0434202ec88a39e3a9c5c2359e1
