### ISSUE TITLE
Add a section on where to find support to the main training

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#58]
Would be helpful to have a paragraph somewhere in Module 1 that covers where people can go for support during the training and after. 

There is already a [section in the wiki](https://giscience.github.io/gis-training-resource-center/content/Wiki/en_qgis_common_errors_and_Issues.html#qgis-help-access-links) that covers this to some extent, but it's missing some official QGIS support channels (mailing lists, Telegram channel, etc.)

**Comment by enauj** [comment]
added section at the bottom of modul_1/en_qgis_start.md
