### ISSUE TITLE
Adjust What is GIS (Theory)

### ISSUE THREAD

**Issue by Alec-SE** [GIScience/gis-training-resource-center#6]
The Paper maps and cartography are quite cool. However, the parts afterwards are out of the scope of this chapter.

The goal of the chapter is to give people an idea of what GIS is. That means we do not need tutorials to do anything in QGIS!

In general, we must not use to technical language!

- [x] The use of headers is not consistent! Please put those in a better order
- [x] The definition part has to be shorter and more visual
- [x] "GIS components", are not relevant
- [x] "What is spatial analysis?" this is much too technical. Here you can use the example of John Snow more extensive
- [x]  The part "Spatial analyses in QGIS" has to be deleted. 
- [x]  Mapping and GIS is redundant and has to be deleted.
- [x] Web GIS and mobile GIS have to be reworked. Here we just want to give a __short__ overview of what's out there.
- [ ]

**Comment by Ingolf25** [comment]
Hi Alec,
I used the headers in a logical way, the system seems not to like when you have several sub-chapters in one chapter. I would like to keep this order. The mentioned chapters are deleted. I will try to shorten "What is spatial analysis?" and  "Web GIS and mobile GIS".
