### ISSUE TITLE
Module 1: What is GIS - separate section for GIS software?

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#64]
I'm not sure [web and mobile GIS applications](https://giscience.github.io/gis-training-resource-center/content/Modul_1/en_qgis_theorie.html#web-mobile-gis-applications) should be under the [Humanitarian map types section](https://giscience.github.io/gis-training-resource-center/content/Modul_1/en_qgis_theorie.html#common-map-types-in-humanitarian-response) - this is more types of GIS software, not specific to humanitarian uses. 

Perhaps GIS software could be a separate section/page and this could be part of it?

**Comment by enauj** [comment]
moved content to appropriate sections
