### ISSUE TITLE
Suggestions for "Buttons and shortcuts" section in Module 1

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#68]
* In the ___[Buttons and shortcuts](https://giscience.github.io/gis-training-resource-center/content/Modul_1/en_qgis_start.html#buttens-and-shortcuts)___ section, wrapping keyboard shortcuts in `kbd` tags will format them nicely - e.g. `<kbd>Ctrl+F</kbd>` will display as <kbd>Ctrl+F</kbd>

* Might be more useful for buttons and shortcuts to appear next to the content they refer to rather than together in a single block

**Comment by enauj** [comment]
I will add the shortcuts as sidebar content as I go over the modules
