### ISSUE TITLE
Adjust "Getting started with QGIS"

### ISSUE THREAD

**Issue by Alec-SE** [GIScience/gis-training-resource-center#7]
The page contains good parts so far. However, some things are out of scope. Concentrate on, what is QGIS, QGIS Installation and the interface

- [x] Add a short part on "What is QGIS". -> Opensource system which is constantly changing...
- [x] Delete the parts on the data import and an attribute table
- [x] Concentrate on the part of the QGIS interface. The is now a [Wiki page on the interface]((https://giscience.github.io/gis-training-resource-center/content/Wiki/en_qgis_interface_wiki.html), you can link to that as well.
- [x] The part on creating a new QGIS project is important and should keept
- [x] The long part with all the videos at the end is not good. You should include the videos right at the relevant position rather than put them all at the end.

**Comment by Ingolf25** [comment]
Done. I changed the display of the videos into the grid view of the mentioned Wiki page.

**Comment by Ingolf25** [comment]
Concerning exercise 3: _Add basemaps_ the original link is broken.
