### ISSUE TITLE
Add a section to explain plugins in Module 1: Getting started with QGIS

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#70]
Specific plugins are mentioned a few times in modules 1 and 2 but I don't think there's an intro/explanation of what plugins are, why you might use them, etc.

**Comment by isikl** [comment]
There is a wiki entry, but nothing in the modules. Maybe add a note for trainers to explain briefly to the participants what Plugins are and how to install them. Add link to wiki for trainers and participants for more information.
