### ISSUE TITLE
Module 3 exercises - errors in URLs

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#71]
The URL for module 3 exercise 1 refers to exercise 2
`https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_digitalisation_`**`ex2`**`.html`

The URL for module 3 exercise 2 refers to exercise 1
`https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_classification_`**`ex1`**`.html`

**Comment by enauj** [comment]
#98
