### ISSUE TITLE
Clarify Spatial Join explanations

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#73]
In the section on [spatial joins](https://giscience.github.io/gis-training-resource-center/content/Modul_5/en_qgis_spatial_tools.html#spatial-joins) - there is potential for confusion between the text descriptions and the [example image](https://giscience.github.io/gis-training-resource-center/content/Modul_5/en_qgis_spatial_tools.html#id1). 

E.g. the description says "Returns 1 (true)" - this could be confused with referring to the shape labelled "1" in the example image. 

Is there another way to word the description or change the image to remove the potential for confusion?

**Comment by enauj** [comment]
rephrased the description to be easier to understand
