### ISSUE TITLE
"Using IFRC symbols" refers to out of date resources

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#79]
[Using IFRC symbols](https://giscience.github.io/gis-training-resource-center/content/Modul_4/en_qgis_map_design_I.html#using-ifrc-symbols) recommends using the resource sharing plugin. 

The humanitarian icons provided in the plugin are old and probably shouldn't be recommended - a better resource to link to would be the [IFRC GO Iconography page](https://go-user-library.ifrc.org/brand-design/iconography)  for IFRC icons and [MapAction's downloads of the OCHA icons](https://github.com/mapaction/ocha-humanitarian-icons-for-gis), which has the latest versions of the OCHA icons, edited to worked well in QGIS.

Could also link to the [IFRC logos directory](https://github.com/ifrcgo/logos), which has logos for all national societies - although that might be more appropriate on a different page (Layout?)

**Comment by enauj** [comment]
i described how to import the IFRC logo repo and the other icons mentioned by @ioalexei.
