### ISSUE TITLE
Restructure Getting started with QGIS

### ISSUE THREAD

**Issue by Alec-SE** [GIScience/gis-training-resource-center#8]
The content is already very good but I think one can structure the subchapter better.

- [x] Move “32 Bit or 64 Bit?” to QGIS Installation
- [x] Have sections: Interface; Move and Zoom; Properties and Toolbars; Projects
- [x] Distribute the videos of "Try out Further Functionalities of QGIS" to the sections above

**Comment by Ingolf25** [comment]
Done. Ich changed back the collapsible tabs to a normal listed. view.
