### ISSUE TITLE
Remove note about HOT Export tool in roads clipping exercise

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#81]
The [roads clipping exercise](https://giscience.github.io/gis-training-resource-center/content/Modul_5/en_qgis_spatial_tools.html#exercise-clipping-a-roads-layer-to-administrative-boundaries) has a note saying the HOT Export Tool is broken - it seems to be working fine now so this message can be removed

**Comment by isikl** [comment]
Link could also be replaced by a new link without failed and empty downloads.
