### ISSUE TITLE
Map layout exercise - add a step to add image/logo

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#84]
in the [map layout](https://giscience.github.io/gis-training-resource-center/content/Modul_4/en_qgis_map_design_I_ex2.html) exercise, can we add a step to insert an image/logo? this is something learners will need to know, so good to let them practice it. 

(also great if we can get them to add the IFRC logo or their own NS, and have the sample image reflect this)

**Comment by enauj** [comment]
Added steps to add logo to print layout
