### ISSUE TITLE
Broken link on Module 3 exercise 2

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#87]
Wiki link not working:  https://giscience.github.io/gis-training-resource-center/content/Wiki/en_qgis_digitalization_wiki.md 

Linked to from  https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_classification_ex1.html#tasks 

"Nr. 7: Add the airports of Bo and Kenema as points to the layer Sierra_Leone_airports. Find help on the addition of features to a point layer [here](https://giscience.github.io/gis-training-resource-center/content/Wiki/en_qgis_digitalization_wiki.md)."

**Comment by ioalexei** [comment]
This might have already been fixed? I can't find the link at the location specified in the feedback

**Comment by isikl** [comment]
Issue still exists. Broken wiki URL is linked in section Tasks, Nr. 7 below the image "Fig. 68 OSM place search."

**Comment by enauj** [comment]
added the correct link
