### ISSUE TITLE
Module 3 Exercise 1: simplify info/instructions?

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#88]
Feedback from a couple of facilitators: 

* Think the first part on digitisation went into too much detail and probably took a bit too long – we don’t need to explain every setting and we can tell users to use the defaults and where to look if they want to understand the options in more detail 

* Even though I have gone through the materials for preparation, I realised during the first section “Digitalisation” that there are many small things to explain especially all the settings in any tools. Thanks you all for chipping in to simplify some of them. It might be nice if the platform could indicate which settings more important and which can ignore, like File encoding: (optional)

--- 

Perhaps we could rely more on the defaults and just give instructions on the bits that _shouldn't_ be left on the default values? 

Since this is still the beginner part of the course, we don't need to explain every option in the dialogue box

**Comment by isikl** [comment]
Digitization exercise: https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_digitalisation_ex2.html

- mention if file creation settings are reffering to geopackage or Shapefile -> there are different setting options available 
- "Remove" points with default settings: "File encoding" and "additional dimension". Maybe add a drop down option below with information on those points in case people want to deep dive?
- The "OSM Place Search" plugin topic in this context is potentially too big, complex and confusing for the participants.  **Suggestions/Ideas:** 
    - Only use OSM baselayer and zoom manually to one country and city and digitize healthsite locations. doesn't matter which ones, but shows the process.  
    - **or**: load satellite imagery OR georeferenced map image and digitize based on that. It is a classic example, shows the purpose of digitizing quite well since (to be correct) you can export and use the OSM data. (provide small orthophoto or image, then people can focus easily on the same area. Maye even same image and example of Fig. 53?) 
    - **or**: when spending time on the plugin topic: introducting the "lat long Tools"? --> quite common situation that people are receving coordinates from the field which can be digitzed. (not talking about a big list of coordinates, but only few)

**Comment by enauj** [comment]
simplified the instruction a bit but i will take a closer look at the digitisation exercise and revamp it further.
