### ISSUE TITLE
Module 2 exercises: error in data URLs and exercise numbering

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#89]
in [Module 2, Exercise 1](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept_ex1.html) - in the [download the data ](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_geodata_concept_ex1.html#data)  section, the link goes to a file that refers to exercise 2: 
`https://nexus.heigit.org/repository/gis-training-resource-center/Modul_2/Modul_2_Exercise2_Geodata_Concept/Modul_2_Exercise2_Geodata_Concept.zip`

[The second exercise](https://giscience.github.io/gis-training-resource-center/content/Modul_2/en_qgis_basic_data_processing_ex1.html) in Module 2 is also listed as exercise 1 in the contents and page URL - should be exercise 2

**Comment by enauj** [comment]
Ordered the exercises: 

Exercise 1: Geodata concept
Exercise 2: Basic Geodata processing
Exercise 3: Data sources
Exercise 4: Exporting OSM data
Exercise 5: The World

File names need to be changed and added to the TOC
