### ISSUE TITLE
Module 2 Exercise 1: CSV data will not load using default import settings

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#90]
The Sierra Leone airports CSV provided in the exercise data won't load using the default Delimited Text Import settings. 

The CSV has a row of HXL tags between the header row and the start of the data - this means that QGIS won't automatically detect the lat/long fields. 

Either the CSV needs to be updated to remove the HXL tags row or the instructions need to include manually specifying the Lat/Long columns in the _Geometry definition_ section of the dialog box.

**Comment by enauj** [comment]
Added explanation to specify lat/long columns in the geometry definitions. 
I will also move this exercise after the geodata management since it is necessary to understand how to load layers and organize data before doing this exercise.
