### ISSUE TITLE
Remake screencast videos that have "Home edition" watermark

### ISSUE THREAD

**Issue by ioalexei** [GIScience/gis-training-resource-center#91]
Videos in the [digitisation](https://giscience.github.io/gis-training-resource-center/content/Modul_3/en_qgis_digitalisation.html) section have a watermark for "Debut Home Edition" - these should be remade with other software so that they don't potentially violate licensing restrictions. 

Check if the same watermark has been used in videos in other sections.

**Comment by enauj** [comment]
done in commit f445d07
